# Generated by Django 5.0.1 on 2024-01-25 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addressBook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='countryID',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='address',
            name='stateID',
            field=models.IntegerField(),
        ),
    ]
