# Generated by Django 5.0.1 on 2024-01-25 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addressBook', '0002_alter_address_countryid_alter_address_stateid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='countryID',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='address',
            name='stateID',
            field=models.CharField(max_length=200),
        ),
    ]
