# Generated by Django 5.0.1 on 2024-01-25 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addressBook', '0004_address_age'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Address',
            new_name='AddressT',
        ),
    ]
